name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: main
      url: https://pypi.org/p/openteleop
    permissions:
      id-token: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure the full history is fetched including tags

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update version in version.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "{\"version\": \"${VERSION}\"}" > version.json
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.json
          git commit -m "Update version to ${VERSION}"
          git push origin HEAD:main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install setuptools

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
